# Generated by Django 6.1.1 on 2026-09-27 06:58

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='kbentry',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('question'), name='gin_trgm_ops'), name='kbentry_question_trgm'),
        ),
        migrations.AddIndex(
            model_name='kbentry',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('answer'), name='gin_trgm_ops'), name='kbentry_answer_trgm'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['queried_at'], name='api_querylo_queried_693aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='querylog',
            index=models.Index(fields=['search_term'], name='api_querylo_search__3b90bd_idx'),
        ),
    ]
